repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline.json"]

  - repo: local
    hooks:
      - id: lint
        name: lint
        language: system
        entry: bun run lint
