# https://github.com/peaceiris/actions-gh-pages
name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency: # https://docs.github.com/ja/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: jurassiscripts/setup-velociraptor@v2
        with:
          deno-version: "1.28.1"

      - name: Build
        working-directory: ./
        run: |
          deno run -A https://deno.land/x/packup@v0.2.2/cli.ts
          vr build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
